site_name: Hams Over IP Wiki
site_url: https://hamsoverip.github.io/wiki
repo_url: https://github.com/hamsoverip/wiki


theme:
  name: 'material'
  features:
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - content.tabs.linked
    - navigation.tabs
    - navigation.tabs.sticky

  # features:
  #   - navigation.expand
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  #- def_list
  - md_in_html
  - pymdownx.blocks.html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      permalink: true


nav:
  - Welcome!: index.md
#  - Latest News: news.md

  - FAQ: guides/faq.md

  - Getting Started:
    - guides/user/getting-started.md
    - Finding Help: guides/user/support.md
    - Joining our Chat Servers: guides/user/chat-services.md
    - Our Social Media: guides/user/social-media.md

  - Configuration Guides:
    - ./guides/index.md
    - Endpoints:
      - guides/endpoints/index.md
      - Hard Phones:
        - guides/endpoints/hardphones/index.md
        - Avaya:
          - Avaya 96xx Series: guides/endpoints/hardphones/avaya-96xx.md
        - Cisco:
          - Cisco 504G/514G: guides/endpoints/hardphones/cisco-504g.md
          - Cisco 508G: guides/endpoints/hardphones/cisco-508g.md
          - Cisco 512G: guides/endpoints/hardphones/cisco-512g.md
          - Cisco 525g: guides/endpoints/hardphones/cisco-525g.md
        - Grandstream:
          - GXP16xx Series: guides/endpoints/hardphones/grandstream-gxp16xx.md
        - OBiHai:
          - OBi202: guides/endpoints/hardphones/obi-202.md
        - Polycom:
          - Polycom VVX-4xx/5xx Series: guides/endpoints/hardphones/polycom-vvx4xx.md
        - Yealink:
          - Yealink T4 Series: guides/endpoints/hardphones/yealink-t4x.md
      - Soft Phones:
        - guides/endpoints/softphones/index.md
        - Groundwire: guides/endpoints/softphones/groundwire.md
        - Jami: guides/endpoints/softphones/jami.md
        - Zoiper: guides/endpoints/softphones/zoiper.md
    - PBX Trunks:
      - guides/pbx/index.md
      - Asterisk:
        - Configure Asterisk IAX Trunk: guides/pbx/asterisk/configure-iax-trunk.md
      - FreePBX: 
        - Configure FreePBX IAX Trunk: guides/pbx/freepbx/configure-iax-trunk.md
        - Configure FreePBX SIP Trunk: guides/pbx/freepbx/configure-sip-trunk.md
      - 3CX PBX:
        - Configure 3CX Trunk: guides/pbx/3cx/configure-3cx-trunk.md
    - RF Links:
      - guides/rf-links/index.md
      - Configure an RF Link: guides/rf-links/configure-rf-links.md
      - Remove SMS:
        - from HamVOIP: guides/rf-links/remove-sms-hamvoip.md
        - from ASL v1 & v2: guides/rf-links/remove-sms-asl-1-2.md
        - from ASL v3: guides/rf-links/remove-sms-asl-3.md
#      - Configure Audio Services: other/configure-audio-feed.md
    - Features:
      - guides/features/index.md
      - Busy Lamp Field (BLF): guides/features/blf.md
      - Lightweight Directory Access Protocol (LDAP): guides/features/ldap.md
      - Conference Menu Codes: guides/features/conference-menu-codes.md
      - PBX Features Codes: guides/features/pbx-feature-codes.md

  - Reference Lists:

    - reference/index.md

    - HOIP Number Lists:
      - Conference Bridges: reference/conference-bridge-list.md
      - RF Links: reference/rf-links-list.md
      - Audio Feeds: reference/audio-feeds-list.md
      - Test Phone Numbers: reference/test-numbers.md

    - Linked VOIP Networks: 
      - reference/linked/index.md
      - AmateurWire: reference/linked/amateurwire.md
      - Global World VOIP: reference/linked/global-world.md
      - Hams Over IP Canada: reference/linked/hamsoverip-ca.md
      - HMASN/AREDN: reference/linked/hmasn-aredn.md
      - MeshPhone: reference/linked/meshphone.md
      - NZSIP: reference/linked/nzsip.md

  - Policies:
    - policies/index.md
#    - Terms of Service: General/coming-soon.md
#    - User Agreement: General/coming-soon.md
    - HOIP Allstar System Rules: policies/hoip-allstar.md

  - Files:
    - files/index.md
    - Phone Wallpaper: wallpaper/wallpaper.md 

  - Wiki:
    - Overview of the Wiki: wiki/overview.md
    - How to Contribute: wiki/contributing.md
    - Changelog: wiki/changelog.md

  - ⬅️ Hams Over IP Website: https://hamsoverip.com


extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/npwFgnj2vU'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/hamsoverip'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/hamsoverip'
    - icon: 'fontawesome/brands/mastodon'
      link: 'https://mastodon.radio/@hamsoverip'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/hamsoverip'


plugins: 
  - redirects:
      redirect_maps:
        "endpoints/index.md": "guides/endpoints/index.md"
        "endpoints/hard_phones/YealinkT4X.md": "guides/endpoints/hardphones/yealink-t4x.md"
        "endpoints/hard_phones/cisco504g.md": "guides/endpoints/hardphones/cisco-504g.md"
        "endpoints/hard_phones/Cisco525.md": "guides/endpoints/hardphones/cisco-525g.md"
        "endpoints/hard_phones/index.md": "guides/endpoints/hardphones/index.md"
        "endpoints/hard_phones/OBi202.md": "guides/endpoints/hardphones/obi-202.md"
        "endpoints/hard_phones/avaya96xx.md": "guides/endpoints/hardphones/avaya-96xx.md"
        "endpoints/hard_phones/PolycomVVX4xx.md": "guides/endpoints/hardphones/polycom-vvx4xx.md"
        "endpoints/hard_phones/cisco512g.md": "guides/endpoints/hardphones/cisco-512g.md"
        "endpoints/hard_phones/cisco508g.md": "guides/endpoints/hardphones/cisco-508g.md"
        "guides/endpoints/hardphones/grandstream-gxp162x.md": "guides/endpoints/hardphones/grandstream-gxp16xx.md"
        "endpoints/soft_phones/jami.md": "guides/endpoints/softphones/jami.md"
        "endpoints/soft_phones/groundwire.md": "guides/endpoints/softphones/groundwire.md"
        "endpoints/soft_phones/index.md": "guides/endpoints/softphones/index.md"
        "endpoints/soft_phones/microsip.md": "guides/endpoints/softphones/microsip.md"
        "endpoints/soft_phones/zoiper.md": "guides/endpoints/softphones/zoiper.md"
        "endpoints/pbx/index.md": "guides/pbx/index.md"
        "endpoints/pbx/3cx/configure-3cx-trunk.md": "guides/pbx/3cx/configure-3cx-trunk.md"
        "endpoints/pbx/asterisk/configure-iax-trunk.md": "guides/pbx/asterisk/configure-iax-trunk.md"
        "endpoints/pbx/freepbx/configure-iax-trunk.md": "guides/pbx/freepbx/configure-iax-trunk.md"
        "endpoints/pbx/freepbx/configure-sip-trunk.md": "guides/pbx/freepbx/configure-sip-trunk.md"
        "endpoints/pbx/freepbx/feature-codes.md": "guides/features/pbx-feature-codes.md"
        "guides/pbx/freepbx/feature-codes.md": "guides/features/pbx-feature-codes.md"

        "General/user_guides/faq.md": "guides/faq.md"
        "General/user_guides/getting-started.md": "guides/user/getting-started.md"
        "General/user_guides/support.md": "guides/user/support.md"
        "General/user_guides/chat-services.md": "guides/user/chat-services.md"
        "General/user_guides/social-media.md": "guides/user/social-media.md"

        "other/conference-bridge-list.md": "reference/conference-bridge-list.md"
        "other/rf-links-list.md": "reference/rf-links-list.md"
        "other/audio-feeds-list.md": "reference/audio-feeds-list.md"
        "other/test-numbers.md": "reference/test-numbers.md"

        "other/configure-rf-links.md": "guides/rf-links/configure-rf-links.md"
        "guides/features/configure-rf-links.md": "guides/rf-links/configure-rf-links.md"
        "other/configure-blf.md": "guides/features/blf.md"
        "guides/features/configure-blf.md": "guides/features/blf.md"
        
        "General/other_systems/index.md": "reference/linked/index.md"
        "General/other_systems/amateurwire.md": "reference/linked/amateurwire.md"
        "General/other_systems/global-world.md": "reference/linked/global-world.md"
        "General/other_systems/hamsoverip-ca.md": "reference/linked/hamsoverip-ca.md"
        "General/other_systems/hmasn-aredn.md": "reference/linked/hmasn-aredn.md"
        "General/other_systems/meshphone.md": "reference/linked/meshphone.md"
        "General/other_systems/nzsip.md": "reference/linked/nzsip.md"

        "General/Policies/hoip-allstar.md": "policies/hoip-allstar.md"

        "General/changelog.md": "wiki/changelog.md"